### ISSUE TITLE
pip-able nbfancy

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#1]
Create pip installable version of build system `nbfancy` and add to pypi 
merge to master
license currently MIT, python generally seems to be BSD3 do we want to switch?

**Comment by JDBetteridge** [comment]
Project (package branch at least) is now pip installable.
Not published to pip but PyPI testing, until we are more ready, see:
https://test.pypi.org/project/nbfancy/0.1.dev1/
