### ISSUE TITLE
Solution, solution, solution

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#11]
Modify solution implementation to currently discussed model:

1.  No solution following exercise, no link appended to exercise cell
2.  md cell: Solution: anything, **single cell solution **
3.  md cell:Solution: start
     **multiple cells or unspecified type**
     Solution: end

Where solution is present:
1.  Append anchored link to Exercise cell 
2.  Solution cell(s) moved to <nbname_>solution
3.  Anchor label generated from current numberth solution

**Comment by JDBetteridge** [comment]
1. Is addressed by adding new keywords now (but don't choose short names like pin or pen)
2. This will use the old machinery of solution environment
3. **multiple cells are hard**, but this is work in progress

I think we already do the following 3 points

**Comment by JDBetteridge** [comment]
Multicell is now available, by adding a `+` to any keyword, and a closing :keyword as the last line of the final cell
