### ISSUE TITLE
Syntac highlighting

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#14]
```brainfuck
syntax highlighting currently requires a language to avoid a bug in certain circumstances.
As this current solution, introduces unwanted highlighting and may cause offence can we resolve the bug or find an alternative, and advised solution
```

**Comment by JDBetteridge** [comment]
[Brainfuck](https://en.wikipedia.org/wiki/Brainfuck) is a language regardless of anyone's opinion on its name. CodeMirror have chosen to include it as a language that they support and it suits our purposes quite well.

People are of course welcome to choose whatever workaround highlighting they want until we can come up with a better solution. I am open to suggestions as to the highlighting we suggest in the tutorial for the workaround, see [here](https://codemirror.net/mode/index.html).

**Comment by JDBetteridge** [comment]
Actually found a workaround using brainfuck. Probably for the best, what if we wanted to make a brainfuck tutorial!!!
