### ISSUE TITLE
key words

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#16]
to simplify the key words, could we remove case sensitivity, 
Also consider using slicing to reduce required length?

**Comment by JDBetteridge** [comment]
Case sensitivity has already been removed, marking issue as solved.

Slicing may additional confusion, especially when introducing custom keywords, we should probably recommend keywords which are single words and insist that these are used, the only current exception being `Key Points`. Another motivation for keeping thing this way is readability of plain notebooks.
