### ISSUE TITLE
Verbalisation

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#7]
Verb enabled: 
nbfancy init # initialise a new instance of nbfancy lesson in `.`, from example with necessary structure
                    # -d <user_specified_directory>
nbfancy build # default build (-d <user_specified_directory> builds to <user_specified_directory>_rend) 
nbfancy custom # create custom config file in `custom` (-f [yaml,csv, ...] ?)

**Comment by JDBetteridge** [comment]
Verbalisation now complete, available verbs are:
- init
- config
- rerun
- render
- html
- hello (Easter Egg!)
